name: Deploy nodejs on ec2 instance

on: 
  push:
    branches: 
      - main

jobs:
  deploy:  
    runs-on:  ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2
      - name:  doploy via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/student-infomation-nodejs
            git pull origin main
            npm install
            pm2 restart all
