name: Deploy nodejs on ec2 instance

on: 
  push:
    branches: 
      - main

jobs:
  deploy:  
    runs-on:  ubuntu-22.04

    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2
      - name:  doploy via ssh
        uses: saranraj3195/sparkout-deployment@v2
        with:
          # SSH private key for authentication
          DEPLOY_KEY: ${secrets.PRIVATE_KEY}
          # SSH username
          USERNAME: ec2-user
          # IP address of the server
          SERVER_IP: "3.14.4.202"
          # SSH port of the server
          SERVER_PORT: "3000"
          # Destination directory on the server
          SERVER_DESTINATION: /home/ec2-user/student-infomation-nodejs

